language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '10'
  - '8'

before_script:
  - npm prune

jobs:
  include:
    - stage: build
      script: yarn build
    - stage: npm release
      script: npm run semantic-release
    - stage: deploy
      script: skip     # usually you do not want to rerun any tests
      deploy:
        skip_cleanup: true
        provider: gae
        keyfile: "secrets-222515-47aa6dc37fe2.json"
        project: "secrets-222515"

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - openssl aes-256-cbc -K $encrypted_c1d8e062b63a_key -iv $encrypted_c1d8e062b63a_iv -in secrets-222515-47aa6dc37fe2.json.enc -out secrets-222515-47aa6dc37fe2.json -d